version: '3.9'
services:
  web:
    image: openzipkin/zipkin
    networks:
      schambeck-net:
        aliases:
          - srv-tracing
    ports:
      - target: 9411
        published: 9411
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
networks:
  schambeck-net:
    external: true
